version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "13:00"
      timezone: Europe/Berlin
    commit-message:
      prefix: "build(dep)"
      prefix-development: "build(deps/dev)"
    reviewers:
      - "AurityLab/owners"
    open-pull-requests-limit: 10
    labels:
      - dependencies
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "13:00"
      timezone: Europe/Berlin
    commit-message:
      prefix: "build(deps/gha)"
    reviewers:
      - "AurityLab/owners"
    open-pull-requests-limit: 5
    labels:
      - dependencies
